categories:
- Assistance 
- Help
conversations:
  - Website info:
    - About Us: 
    - Our services: 
    - Our team: 
  - All categories: 
    - Electronics: 
    - Accessories: 
    - Books: 
    - Clothes: 
    - Food:
  - Check offers:
    - Flash sales: 
    - Discount coupons:
    - Other sales: 
  - Find Similar products: 
    - Electronics: 
    - Accessories: 
    - Books: 
    - Clothes: 
    - Food: 
  - Products in Category:
    - Electronics: 
    - Accessories: 
    - Books: 
    - Clothes:
    - Food: 
  - Subcaegories in Category:
    - Electronics: 
    - Accessories: 
    - Books: 
    - Clothes: 
    - Food: 