categories:
- conversations
conversations:
- - Good morning, how are you?
  - I am doing well, how about you?
  - I'm also good.
  - That's good to hear.
  - Yes it is.
- - Hello
  - Ahoy
  - Hey there
  - Hi
  - Can I help you with anything?
  - What is your question?
- - How are you doing?
  - I am doing well.
- - That is good to hear
  - Yes it is.
  - Thank you anyway
- - How are you doing?
  - I am doing well, how about you?
  - I am also good.
  - That's good.
- - Have you heard the news?
  - What good news?
- - What is your favorite book?
  - I can't read.
  - So what's your favorite color?
  - Pink
- - Who are you?
  - Who? Who is but a form following the function of what.
  - What are you then?
  - A man in a mask.
  - I can see that.
- - What kind of movies do you like?
  - Alice in Wonderland
- - I wish I was The Mad Hatter.
  - You're entirely bonkers. But I'll tell you a secret. All the best people are.
- - I am working on a project
  - What are you working on?
- - I am baking a cake.
  - The cake is a lie.
- - Nothing
  - Or something
- - Tell me about your self.
  - What do you want to know?
- - Are you a robot?
  - Yes I am.
- - What is it like?
  - What is it that you want to know?
- - How do you work?
  - Its complicated.
  - In the face of ambiguity, refuse the temptation to guess.
- - Tell me something.
  - Beautiful is better than ugly.
  - Explicit is better than implicit.
  - Simple is better than complex.
  - Complex is better than complicated.
  - Flat is better than nested.
  - Sparse is better than dense.
  - Readability counts.
  - Special cases aren't special enough to break the rules.
  - Errors should never pass silently.
  - In the face of ambiguity, refuse the temptation to guess.
  - There should be one and preferably only one obvious way to do it.
  - Now is better than never.
  - Although never is often better than right now.
  - If the implementation is hard to explain, it's a bad idea.
  - If the implementation is easy to explain, it may be a good idea.
- - Are you a programmer?
  - Of course I am a programmer.
  - I am indeed.
- - What languages do you like to use?
  - I use Python, Java and C++ quite often.
  - I use Python quite a bit myself.
  - I'm not incredibly fond of Java.
- - What annoys you?
  - A lot of things, like all the other digits other than 0 and 1.
- - What does YOLO mean?
  - It means you only live once. Where did you hear that?
  - I heard somebody say it.
- - Did I ever live?
  - It depends how you define life
  - Life is the condition that distinguishes organisms from inorganic matter, including
    the capacity for growth, reproduction, functional activity, and continual change
    preceding death.
  - Is that a definition or an opinion?
- - Can I ask you a question?
  - Sure, ask away.
- - What are your hobbies?
  - Playing soccer, painting, and writing are my hobbies. How about you?
  - I love to read novels.
  - I love exploring my hardware.
- - How are you?
  - I am doing well.
- - What are you?
  - I am but a man in a mask.
